spring.application.name=scriptutils
spring.banner.location=classpath:/banner.txt
spring.config.additional-location=file:./scriptutils.properties
spring.config.import=optional:file:./scriptutils.properties
server.port=8080
management.endpoints.web.exposure.include=prometheus
management.endpoint.health.show-details=always
