spring.application.name=scriptutils
spring.banner.location=classpath:/banner.txt
spring.config.additional-location=file:./scriptutils.properties
spring.config.import=optional:file:./scriptutils.properties
